#!/bin/sh -efu

# Обновить перевалы.
# Перевалы скачиваются с сайта Вестры в виде KML, преобразуются в MP+TXT.
# Обновляется VMAP, если есть файл wpasses/<name>_wp.sed, то vmap фильтруется.
# Если в директории IN есть fig-файл, то он обновляется.


# map_wp_upd_nom -- update passes
# example: map_wp_upd_nom j43-061 j43-062

# VMAP files are taken from ./vmap/ dir
# Data is stored in ./wpasses/ dir

##############

# get url for downloading data from westra pass catalog
# usage:  ll2wp <wgs lonlat geom>
ll2wp(){
  local geom="$1"

  echo "$geom" |
  sed 's/^\[\([0-9\.-]\+\) *, *\([0-9\.-]\+\) *, *\([0-9\.-]\+\) *, *\([0-9\.-]\+\)\]/\1 \2 \3 \4/' |
  {
    local x1 x2 y1 y2 dx dy
    read x1 y1 dx dy
    x2="$(printf -- "${x1#+} + $dx\n" | bc -l)"
    y2="$(printf -- "${y1#+} + $dy\n" | bc -l)"
    printf "http://westra.ru/passes/kml/passes.php?BBOX=%f,%f,%f,%f" $x1 $y1 $x2 $y2
  }
}


mkdir -p -- wpasses
for i in "$@"; do
  base=$(basename ${i%.*})
  echo $i

  # WGS range
  g="$(ms2nom --wgs --ext --name "$base")"

  # download
  wget "$(ll2wp "$g")" -O - > "wpasses/${base}_wp.kml"

  mapsoft_wp_parse "wpasses/${base}_wp.kml"

  mapsoft_vmap -v \
    wpasses/${base}_wp.mp --set_source westra_passes\
       --range_nom "$base" --range_action="select"\
    "$i" --split_labels --skip_source westra_passes\
    -o "$i"

  sed_args=''
  if [ -f "wpasses.sed" ];            then sed_args="$sed_args --file wpasses.sed"; fi
  if [ -f "wpasses/${base}_wp.sed" ]; then sed_args="$sed_args --file wpasses/${base}_wp.sed"; fi
  if [ -n "$sed_args" ]; then
    sed -r -i -e '/^OBJECT\t0x(67..|64..|1100)/{' $sed_args -e "}" "$i"
  fi

  rm -f -- "wpasses/${base}_wp.mp"

  # update fig if needed
  if [ -f IN/$base.fig ]; then
    cd IN
    ./map_get_fig "$base.fig"
    cd ..
  fi

done
