#!/bin/sh -e

ins=$(echo j43-{098,099,100,110,111,112}.vmap)
out=j43-110.3x2

echo $ins

mapsoft_vmap -v $ins --out $out.vmap --range_nom $out\
    --set_brd_from_range  --name "$out"

mapsoft_vmap -v $out.vmap --out $out.vmap --join_objects 1e-4