#!/bin/sh -efu

# get fig files for editing

figdir="../fig"
vmapdir="../vmap"
rscale=100000

for name in "$@"; do
  base=$(basename ${name%.*})
  name="$base.fig"
  cp -f -- "$figdir/$name" "$name" ||:

  range=$(sed -ne "s/$base\s\+//p" ../maps.txt)
  [ -n "$range" ] || range="$base"

  ~/mapsoft/programs/mapsoft_vmap --range_nom "$range" --set_brd_from_range\
            --name "$base" --rscale "$rscale"\
            "$vmapdir/$base.vmap" -o "$name"
done
