#!/bin/sh -eu

map_rscale=100000
nom_rscale=$map_rscale

. mapsoft_crd.sh

src_dir="../vmap"
lab_dir="labels"
fig_dir="fig"

######################################################################

mkdir -p -- "$fig_dir"

while read name geom title; do
  [ -n "${name%#*}" ] || continue

  echo "$name $geom $title"

  l="$lab_dir/$name.vmap"
  f="$fig_dir/$name.fig"

  src=''; need_update=''
  for n in $(geom2nom "$geom" "$nom_rscale"); do
    s="$src_dir/$n.vmap"
    if [ -f "$s" ]; then
      src="$src $s";
      [ -f "$f" -a "$s" -ot "$f" ] || need_update=1
    else
      echo "warning: can't find file $s"
    fi
  done
  [ -n "$need_update" ] || continue

  # create labels if not exists
  if [ ! -f "$l" ]; then
    vmap_copy -v $src -o "$l" --skip_all --split_labels
  fi

  brd=''
  if [ -f "$f" ]; then
    brd="--keep_border"
  else
    mapsoft_geofig create --datum pulkovo --geom tmerc --geom "$geom"\
                          --rscale "$map_rscale" -o "$f"
    brd="--set_brd_from_range"
  fi

  mapsoft_vmap -v $src --out tmp.vmap\
    --range_datum pulk --range_proj tmerc --range "$geom"\
    --range_action crop_spl
  mapsoft_vmap tmp.vmap --skip_labels "$l"\
    -o "$f" --range_datum pulk --range_proj tmerc --range "$geom"\
    --join_objects 1e-4 $brd --name "$title" --rscale "$map_rscale"
  rm -f tmp.vmap
done < maps.txt
